import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class NewJFramemain extends javax.swing.JFrame {

    public NewJFramemain() {
        initComponents();
        setBlackBackground();
    }

    private void setBlackBackground() {
        pnlmain.setBackground(Color.BLACK);
        lbltitle.setBackground(new Color(153, 0, 153));
        lbltitle.setForeground(Color.WHITE);
        lblsub.setForeground(Color.WHITE);
        lbln2.setForeground(Color.WHITE);
        lbln3.setForeground(Color.WHITE);
        txtn1.setBackground(new Color(153, 0, 153));
        txtn1.setForeground(Color.YELLOW);
        txtn2.setBackground(new Color(153, 0, 153));
        txtn2.setForeground(Color.YELLOW);
        btnadd.setBackground(new Color(153, 0, 153));
        btnadd.setForeground(Color.WHITE);
        btnsub.setBackground(new Color(153, 0, 153));
        btnsub.setForeground(Color.WHITE);
        btnmul.setBackground(new Color(153, 0, 153));
        btnmul.setForeground(Color.WHITE);
        btndiv.setBackground(new Color(153, 0, 153));
        btndiv.setForeground(Color.WHITE);
        txtres.setBackground(new Color(153, 0, 153));
        txtres.setForeground(Color.YELLOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new java.awt.Panel();
        lbltitle = new java.awt.Label();
        lblsub = new java.awt.Label();
        lbln2 = new java.awt.Label();
        txtn1 = new java.awt.TextField();
        txtn2 = new java.awt.TextField();
        lbln3 = new java.awt.Label();
        btnadd = new java.awt.Button();
        btnmul = new java.awt.Button();
        btnsub = new java.awt.Button();
        btndiv = new java.awt.Button();
        txtres = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlmain.setBackground(new java.awt.Color(204, 204, 204));

        lbltitle.setAlignment(java.awt.Label.CENTER);
        lbltitle.setBackground(new java.awt.Color(153, 0, 153));
        lbltitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setText("Calculator");

        lblsub.setAlignment(java.awt.Label.CENTER);
        lblsub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblsub.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblsub.setText("Choose the below operation");

        lbln2.setAlignment(java.awt.Label.CENTER);
        lbln2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbln2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbln2.setText("Number2");

        txtn1.setBackground(new java.awt.Color(153, 0, 153));
        txtn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtn1.setForeground(new java.awt.Color(255, 255, 0));
        txtn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn1KeyTyped(evt);
            }
        });

        txtn2.setBackground(new java.awt.Color(153, 0, 153));
        txtn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtn2.setForeground(new java.awt.Color(255, 255, 0));
        txtn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn2KeyTyped(evt);
            }
        });

        lbln3.setAlignment(java.awt.Label.CENTER);
        lbln3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbln3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lbln3.setText("Number1");

        btnadd.setBackground(new java.awt.Color(153, 0, 153));
        btnadd.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setLabel("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnmul.setBackground(new java.awt.Color(153, 0, 153));
        btnmul.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnmul.setForeground(new java.awt.Color(255, 255, 255));
        btnmul.setLabel("MUL");
        btnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmulActionPerformed(evt);
            }
        });

        btnsub.setBackground(new java.awt.Color(153, 0, 153));
        btnsub.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnsub.setForeground(new java.awt.Color(255, 255, 255));
        btnsub.setLabel("SUB");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });

        btndiv.setBackground(new java.awt.Color(153, 0, 153));
        btndiv.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btndiv.setForeground(new java.awt.Color(255, 255, 255));
        btndiv.setLabel("DIV");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });

        txtres.setBackground(new java.awt.Color(153, 0, 153));
        txtres.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtres.setForeground(new java.awt.Color(255, 255, 0));
        txtres.setText("Result here");

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
                pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlmainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlmainLayout.createSequentialGroup()
                                                .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(pnlmainLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lbln3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                                .addComponent(lbln2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmainLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                        .addGroup(pnlmainLayout.createSequentialGroup()
                                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlmainLayout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(lblsub, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlmainLayout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnlmainLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
                pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlmainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbln2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbln3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnmul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtn1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn1KeyTyped
        char ch;
        ch=evt.getKeyChar();
        if((txtn1.getText().isBlank()==true)&&(ch=='+'||ch=='-'))
        {

        }
        else if(Character.isDigit(ch)==false)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtn1KeyTyped

    private void txtn2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn2KeyTyped
        char ch;
        ch=evt.getKeyChar();
        if((txtn1.getText().isBlank()==true)&&(ch=='+'||ch=='-'))
        {

        }
        else if(Character.isDigit(ch)==false)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtn2KeyTyped

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String n1,n2;
        n1=txtn1.getText();
        n2=txtn2.getText();
        while(txtn1.getText().isBlank())
        {
            txtn1.setText("give input!!!");

        }
        while(txtn2.getText().isBlank())
        {
            txtn2.setText("give input!!!");
        }
        int num1,num2;
        num1=Integer.parseInt(n1);
        num2=Integer.parseInt(n2);
        int i=num1+num2;
        //System.out.println(i);
        txtres.setText("ADDITION:"+i);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        String n1,n2;
        n1=txtn1.getText();
        n2=txtn2.getText();
        while(txtn1.getText().isBlank())
        {
            txtn1.setText("give input!!!");

        }
        while(txtn2.getText().isBlank())
        {
            txtn2.setText("give input!!!");
        }
        int num1,num2;
        num1=Integer.parseInt(n1);
        num2=Integer.parseInt(n2);
        int i=num1-num2;
        //System.out.println(i);
        txtres.setText("SUBTRACTION:"+i);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubActionPerformed

    private void btnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmulActionPerformed
        String n1,n2;
        n1=txtn1.getText();
        n2=txtn2.getText();
        while(txtn1.getText().isBlank())
        {
            txtn1.setText("give input!!!");

        }
        while(txtn2.getText().isBlank())
        {
            txtn2.setText("give input!!!");
        }
        int num1,num2;
        num1=Integer.parseInt(n1);
        num2=Integer.parseInt(n2);
        int i=num1*num2;
        //System.out.println(i);
        txtres.setText("MULTIPLICATION:"+i);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmulActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {
        String n1, n2;
        n1 = txtn1.getText();
        n2 = txtn2.getText();
        while (txtn1.getText().isBlank()) {
            txtn1.setText("give input!!!");
        }
        while (txtn2.getText().isBlank()) {
            txtn2.setText("give input!!!");
        }
        double num1, num2;
        num1 = Double.parseDouble(n1);
        num2 = Double.parseDouble(n2);
        if (num2 == 0) {
            txtres.setText("Cannot divide by zero!");
        } else {
            double result = num1 / num2;
            txtres.setText("DIVISION: " + result);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFramemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFramemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFramemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFramemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFramemain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnadd;
    private java.awt.Button btndiv;
    private java.awt.Button btnmul;
    private java.awt.Button btnsub;
    private java.awt.Label lbln2;
    private java.awt.Label lbln3;
    private java.awt.Label lblsub;
    private java.awt.Label lbltitle;
    private java.awt.Panel pnlmain;
    private java.awt.TextField txtn1;
    private java.awt.TextField txtn2;
    private java.awt.TextField txtres;
    // End of variables declaration//GEN-END:variables
}
